name: Docker Image CI_customer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm install
          npm install typescript@5.5.2 --save-dev # Install TypeScript version 5.5.2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: docker.io
          username: ${{ secrets.NEW_ACR_USERNAME }}
          password: ${{ secrets.NEW_ACR_PASSWORD }}
          
      - name: Build the Docker image
        run: docker build . --file ./docker/dev/Dockerfile --tag event-ticket

      - name: Tag the Docker image
        run: docker tag event-ticket docker.io/wheelerthegreat/event-ticket:v1.0.0

      - name: Push the Docker image to ACR
        run: docker push docker.io/wheelerthegreat/event-ticket:v1.0.0